# Generated by Django 3.2.9 on 2021-11-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messages',
            field=models.TextField(default='message'),
        ),
    ]
